input {
    file{
        path => "/logs/*.log"
        start_position => "beginning"
        codec => plain { charset => "UTF-8" }
    }
}

filter {
        ruby {
            code => "event.set('index_name',event.get('path').split('/')[-1].gsub('.log',''))"
        }
}

output {
    elasticsearch {
        hosts => ["elasticsearch:9200"]
		index => "%{index_name}"
    }
}